### ISSUE TITLE
Make projects runnable - usability of Web projects

### ISSUE THREAD

**Issue by t0yv0** [intellifactory/monodevelop.websharper#4]
This may need to be fixed in W# itself. Currently none of the projects except the "Sitelet Host" project are runnable, and that one is not easy to use (requires creating and referencing a sitelet project). Should make these possible, or at least include a README.

**Comment by MangelMaxime** [comment]
Depending on the project you used you can run your project with `xsp4` command line from project folder.

And for the bundle project, it's just html, js, and css files. So you have nothing to do than loading your index file. Make sure you edit the index file to replace `$safeprojectname$`by your project name.

**Comment by Tarmil** [comment]
Fixed since d2fa66010f8e988fc79d228eb94c3d3aa8d9501b
