### ISSUE TITLE
Bundle Website index.html has to be manually edited

### ISSUE THREAD

**Issue by adamchester** [intellifactory/monodevelop.websharper#9]
![image](https://cloud.githubusercontent.com/assets/570470/3441820/5dccbe58-010a-11e4-9586-858abf9e9731.png)

Presumably, the `$safeprojectname$` should be replaced with the actual project name.

**Comment by Tarmil** [comment]
Fixed upstream in [websharper.visualstudio](https://github.com/intellifactory/websharper.visualstudio/commit/ff6a3322a1dec307072645f973a6fb36228f035c), the addin version 3.0.36.1 includes this fix.
